Added caching policies for /customer/account/*
- This introduce a "bug". Due to another "Unpaid Intern" the caching
  policy applied to the "sales.order.history" block generates an
exception: Fatal error: Call to a member function setHeaderTitle() on a
non-object in
/magento-1.6.1.0/app/code/core/Mage/Sales/Block/Order/History.php
on line 52

If you want to fix this problem, you need to override
Mage_Sales_Block_Order_History and comment out line 52.

Yes, I know, it's ugly.